source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings!

platform :ios, '8.0'

use_frameworks!

target 'JTFMDB_Example', :exclusive => true do
  pod "JTFMDB", :path => "../"
end

target 'JTFMDB_Tests', :exclusive => true do
  pod "JTFMDB", :path => "../"

  
end
