source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'JTFMDB_Example', :exclusive => true do
  pod "JTFMDB", :path => "../"
end

target 'JTFMDB_Tests', :exclusive => true do
  pod "JTFMDB", :path => "../"

  
end
